=== api-evangelist/wordnik/json-schema/wordnik-definition-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/wordnik/refs/heads/main/json-schema/wordnik-definition-schema.json",
  "title": "Definition",
  "description": "Definition schema from Wordnik",
  "type": "object",
  "properties": {
    "attributionText": {
      "type": "string"
    },
    "attributionUrl": {
      "type": "string"
    },
    "citations": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Citation"
      }
    },
    "exampleUses": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/ExampleUsage"
      }
    },
    "extendedText": {
      "type": "string"
    },
    "labels": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Label"
      }
    },
    "notes": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Note"
      }
    },
    "partOfSpeech": {
      "type": "string"
    },
    "relatedWords": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Related"
      }
    },
    "score": {
      "type": "number",
      "format": "float"
    },
    "seqString": {
      "type": "string"
    },
    "sequence": {
      "type": "string"
    },
    "sourceDictionary": {
      "type": "string",
      "example": "ahd-5"
    },
    "text": {
      "type": "string"
    },
    "textProns": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/TextPron"
      }
    },
    "word": {
      "type": "string"
    }
  }
}

=== api-evangelist/wordnik/examples/wordnik-definition-example.json
{
  "attributionText": "Example display string",
  "attributionUrl": "https://wordnik.com/words/serendipity",
  "citations": [
    null,
    null
  ],
  "exampleUses": [
    null,
    null
  ],
  "extendedText": "Example display string",
  "labels": [
    null,
    null
  ],
  "notes": [
    null,
    null
  ],
  "partOfSpeech": "example",
  "relatedWords": [
    null,
    null
  ],
  "score": 9.13,
  "seqString": "example",
  "sequence": "example",
  "sourceDictionary": "ahd-5",
  "text": "Example display string",
  "textProns": [
    null,
    null
  ],
  "word": "serendipity"
}
