=== api-evangelist/wordnik/json-schema/wordnik-word-list-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/wordnik/refs/heads/main/json-schema/wordnik-word-list-schema.json",
  "title": "WordList",
  "description": "WordList schema from Wordnik",
  "type": "object",
  "properties": {
    "createdAt": {
      "type": "string",
      "format": "date-time"
    },
    "description": {
      "type": "string"
    },
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "lastActivityAt": {
      "type": "string",
      "format": "date-time"
    },
    "name": {
      "type": "string"
    },
    "numberWordsInList": {
      "type": "integer",
      "format": "int64"
    },
    "permalink": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": [
        "PUBLIC",
        "PRIVATE"
      ]
    },
    "updatedAt": {
      "type": "string",
      "format": "date-time"
    },
    "userId": {
      "type": "integer",
      "format": "int64"
    },
    "username": {
      "type": "string"
    }
  },
  "required": [
    "id"
  ]
}

=== api-evangelist/wordnik/examples/wordnik-word-list-example.json
{
  "createdAt": "2026-05-29T14:30:00Z",
  "description": "example",
  "id": 500123,
  "lastActivityAt": "2026-05-29T14:30:00Z",
  "name": "Jane Smith",
  "numberWordsInList": 1718153645993,
  "permalink": "favorite-words",
  "type": "PUBLIC",
  "updatedAt": "2026-05-29T14:30:00Z",
  "userId": 500123,
  "username": "Jane Smith"
}
